parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''

api_platform:
    defaults:
        cache_headers:
            max_age: 0
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization']
            invalidation:
                enabled: true
                varnish_urls: ['%env(VARNISH_URL)%']
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: Seed API Platform
    version: 1.0.0
    # Enable the Varnish integration
    http_cache:
        public: true
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
